/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.educationloan.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DocumentUploadedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1029534074306869438L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentUploadedEvent\",\"namespace\":\"com.educationloan.events\",\"fields\":[{\"name\":\"documentId\",\"type\":\"long\"},{\"name\":\"applicantId\",\"type\":\"long\"},{\"name\":\"documentType\",\"type\":\"string\"},{\"name\":\"fileUrl\",\"type\":\"string\"},{\"name\":\"uploadedAt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DocumentUploadedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentUploadedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentUploadedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentUploadedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentUploadedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentUploadedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentUploadedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentUploadedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentUploadedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long documentId;
  private long applicantId;
  private java.lang.CharSequence documentType;
  private java.lang.CharSequence fileUrl;
  private java.lang.CharSequence uploadedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentUploadedEvent() {}

  /**
   * All-args constructor.
   * @param documentId The new value for documentId
   * @param applicantId The new value for applicantId
   * @param documentType The new value for documentType
   * @param fileUrl The new value for fileUrl
   * @param uploadedAt The new value for uploadedAt
   */
  public DocumentUploadedEvent(java.lang.Long documentId, java.lang.Long applicantId, java.lang.CharSequence documentType, java.lang.CharSequence fileUrl, java.lang.CharSequence uploadedAt) {
    this.documentId = documentId;
    this.applicantId = applicantId;
    this.documentType = documentType;
    this.fileUrl = fileUrl;
    this.uploadedAt = uploadedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return documentId;
    case 1: return applicantId;
    case 2: return documentType;
    case 3: return fileUrl;
    case 4: return uploadedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: documentId = (java.lang.Long)value$; break;
    case 1: applicantId = (java.lang.Long)value$; break;
    case 2: documentType = (java.lang.CharSequence)value$; break;
    case 3: fileUrl = (java.lang.CharSequence)value$; break;
    case 4: uploadedAt = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'documentId' field.
   * @return The value of the 'documentId' field.
   */
  public long getDocumentId() {
    return documentId;
  }


  /**
   * Sets the value of the 'documentId' field.
   * @param value the value to set.
   */
  public void setDocumentId(long value) {
    this.documentId = value;
  }

  /**
   * Gets the value of the 'applicantId' field.
   * @return The value of the 'applicantId' field.
   */
  public long getApplicantId() {
    return applicantId;
  }


  /**
   * Sets the value of the 'applicantId' field.
   * @param value the value to set.
   */
  public void setApplicantId(long value) {
    this.applicantId = value;
  }

  /**
   * Gets the value of the 'documentType' field.
   * @return The value of the 'documentType' field.
   */
  public java.lang.CharSequence getDocumentType() {
    return documentType;
  }


  /**
   * Sets the value of the 'documentType' field.
   * @param value the value to set.
   */
  public void setDocumentType(java.lang.CharSequence value) {
    this.documentType = value;
  }

  /**
   * Gets the value of the 'fileUrl' field.
   * @return The value of the 'fileUrl' field.
   */
  public java.lang.CharSequence getFileUrl() {
    return fileUrl;
  }


  /**
   * Sets the value of the 'fileUrl' field.
   * @param value the value to set.
   */
  public void setFileUrl(java.lang.CharSequence value) {
    this.fileUrl = value;
  }

  /**
   * Gets the value of the 'uploadedAt' field.
   * @return The value of the 'uploadedAt' field.
   */
  public java.lang.CharSequence getUploadedAt() {
    return uploadedAt;
  }


  /**
   * Sets the value of the 'uploadedAt' field.
   * @param value the value to set.
   */
  public void setUploadedAt(java.lang.CharSequence value) {
    this.uploadedAt = value;
  }

  /**
   * Creates a new DocumentUploadedEvent RecordBuilder.
   * @return A new DocumentUploadedEvent RecordBuilder
   */
  public static com.educationloan.events.DocumentUploadedEvent.Builder newBuilder() {
    return new com.educationloan.events.DocumentUploadedEvent.Builder();
  }

  /**
   * Creates a new DocumentUploadedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentUploadedEvent RecordBuilder
   */
  public static com.educationloan.events.DocumentUploadedEvent.Builder newBuilder(com.educationloan.events.DocumentUploadedEvent.Builder other) {
    if (other == null) {
      return new com.educationloan.events.DocumentUploadedEvent.Builder();
    } else {
      return new com.educationloan.events.DocumentUploadedEvent.Builder(other);
    }
  }

  /**
   * Creates a new DocumentUploadedEvent RecordBuilder by copying an existing DocumentUploadedEvent instance.
   * @param other The existing instance to copy.
   * @return A new DocumentUploadedEvent RecordBuilder
   */
  public static com.educationloan.events.DocumentUploadedEvent.Builder newBuilder(com.educationloan.events.DocumentUploadedEvent other) {
    if (other == null) {
      return new com.educationloan.events.DocumentUploadedEvent.Builder();
    } else {
      return new com.educationloan.events.DocumentUploadedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentUploadedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentUploadedEvent>
    implements org.apache.avro.data.RecordBuilder<DocumentUploadedEvent> {

    private long documentId;
    private long applicantId;
    private java.lang.CharSequence documentType;
    private java.lang.CharSequence fileUrl;
    private java.lang.CharSequence uploadedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.educationloan.events.DocumentUploadedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.documentId)) {
        this.documentId = data().deepCopy(fields()[0].schema(), other.documentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.applicantId)) {
        this.applicantId = data().deepCopy(fields()[1].schema(), other.applicantId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.documentType)) {
        this.documentType = data().deepCopy(fields()[2].schema(), other.documentType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.fileUrl)) {
        this.fileUrl = data().deepCopy(fields()[3].schema(), other.fileUrl);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.uploadedAt)) {
        this.uploadedAt = data().deepCopy(fields()[4].schema(), other.uploadedAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentUploadedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.educationloan.events.DocumentUploadedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.documentId)) {
        this.documentId = data().deepCopy(fields()[0].schema(), other.documentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.applicantId)) {
        this.applicantId = data().deepCopy(fields()[1].schema(), other.applicantId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.documentType)) {
        this.documentType = data().deepCopy(fields()[2].schema(), other.documentType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fileUrl)) {
        this.fileUrl = data().deepCopy(fields()[3].schema(), other.fileUrl);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.uploadedAt)) {
        this.uploadedAt = data().deepCopy(fields()[4].schema(), other.uploadedAt);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'documentId' field.
      * @return The value.
      */
    public long getDocumentId() {
      return documentId;
    }


    /**
      * Sets the value of the 'documentId' field.
      * @param value The value of 'documentId'.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder setDocumentId(long value) {
      validate(fields()[0], value);
      this.documentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'documentId' field has been set.
      * @return True if the 'documentId' field has been set, false otherwise.
      */
    public boolean hasDocumentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'documentId' field.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder clearDocumentId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'applicantId' field.
      * @return The value.
      */
    public long getApplicantId() {
      return applicantId;
    }


    /**
      * Sets the value of the 'applicantId' field.
      * @param value The value of 'applicantId'.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder setApplicantId(long value) {
      validate(fields()[1], value);
      this.applicantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'applicantId' field has been set.
      * @return True if the 'applicantId' field has been set, false otherwise.
      */
    public boolean hasApplicantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'applicantId' field.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder clearApplicantId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentType' field.
      * @return The value.
      */
    public java.lang.CharSequence getDocumentType() {
      return documentType;
    }


    /**
      * Sets the value of the 'documentType' field.
      * @param value The value of 'documentType'.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder setDocumentType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.documentType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'documentType' field has been set.
      * @return True if the 'documentType' field has been set, false otherwise.
      */
    public boolean hasDocumentType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'documentType' field.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder clearDocumentType() {
      documentType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'fileUrl' field.
      * @return The value.
      */
    public java.lang.CharSequence getFileUrl() {
      return fileUrl;
    }


    /**
      * Sets the value of the 'fileUrl' field.
      * @param value The value of 'fileUrl'.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder setFileUrl(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.fileUrl = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'fileUrl' field has been set.
      * @return True if the 'fileUrl' field has been set, false otherwise.
      */
    public boolean hasFileUrl() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'fileUrl' field.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder clearFileUrl() {
      fileUrl = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'uploadedAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getUploadedAt() {
      return uploadedAt;
    }


    /**
      * Sets the value of the 'uploadedAt' field.
      * @param value The value of 'uploadedAt'.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder setUploadedAt(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.uploadedAt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'uploadedAt' field has been set.
      * @return True if the 'uploadedAt' field has been set, false otherwise.
      */
    public boolean hasUploadedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'uploadedAt' field.
      * @return This builder.
      */
    public com.educationloan.events.DocumentUploadedEvent.Builder clearUploadedAt() {
      uploadedAt = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentUploadedEvent build() {
      try {
        DocumentUploadedEvent record = new DocumentUploadedEvent();
        record.documentId = fieldSetFlags()[0] ? this.documentId : (java.lang.Long) defaultValue(fields()[0]);
        record.applicantId = fieldSetFlags()[1] ? this.applicantId : (java.lang.Long) defaultValue(fields()[1]);
        record.documentType = fieldSetFlags()[2] ? this.documentType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.fileUrl = fieldSetFlags()[3] ? this.fileUrl : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.uploadedAt = fieldSetFlags()[4] ? this.uploadedAt : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentUploadedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentUploadedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentUploadedEvent>
    READER$ = (org.apache.avro.io.DatumReader<DocumentUploadedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.documentId);

    out.writeLong(this.applicantId);

    out.writeString(this.documentType);

    out.writeString(this.fileUrl);

    out.writeString(this.uploadedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.documentId = in.readLong();

      this.applicantId = in.readLong();

      this.documentType = in.readString(this.documentType instanceof Utf8 ? (Utf8)this.documentType : null);

      this.fileUrl = in.readString(this.fileUrl instanceof Utf8 ? (Utf8)this.fileUrl : null);

      this.uploadedAt = in.readString(this.uploadedAt instanceof Utf8 ? (Utf8)this.uploadedAt : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.documentId = in.readLong();
          break;

        case 1:
          this.applicantId = in.readLong();
          break;

        case 2:
          this.documentType = in.readString(this.documentType instanceof Utf8 ? (Utf8)this.documentType : null);
          break;

        case 3:
          this.fileUrl = in.readString(this.fileUrl instanceof Utf8 ? (Utf8)this.fileUrl : null);
          break;

        case 4:
          this.uploadedAt = in.readString(this.uploadedAt instanceof Utf8 ? (Utf8)this.uploadedAt : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










